services:
  - type: web
    name: aventurape-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /sign-in
        destination: /index.html
      - type: rewrite
        source: /sign-up
        destination: /index.html
      - type: rewrite
        source: /sign-in-admin
        destination: /index.html
      - type: rewrite
        source: /sign-up-admin
        destination: /index.html
      - type: rewrite
        source: /admin-home
        destination: /index.html
      - type: rewrite
        source: /adventurous-home
        destination: /index.html
      - type: rewrite
        source: /entrepreneur-home
        destination: /index.html
      - type: rewrite
        source: /dashboard
        destination: /index.html
      - type: rewrite
        source: /activity/*
        destination: /index.html
      - type: rewrite
        source: /profile/*
        destination: /index.html
      - type: rewrite
        source: /statistics/*
        destination: /index.html
      - type: rewrite
        source: /admin/*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://tu-api-backend.onrender.com/api/v1
      - key: VITE_APP_TITLE
        value: AventuraPE
      - key: VITE_APP_ENV
        value: production
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable 